### ISSUE TITLE
mkosi/ci: list of further improvements

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#35492]
- [x] Check and extract sanitizer reports.
WIP PRs : #35480, #35482

- [ ] Enable sanitizer to PID1/journald ? See https://github.com/systemd/systemd/blob/560412148fa62d779ea522d43960dd3acd44b261/test/test-functions#L924-L928
To make sure it works it should be possible to introduce memory leaks to PID1/journald to see whether they can be detected.

- [ ] ASan backtraces aren't always symbolized: https://github.com/systemd/systemd/pull/34640#issuecomment-2618858010

- [ ] The other backtraces aren't always symbolized either: https://github.com/systemd/systemd/pull/36353#issuecomment-2652920633

- [ ] Run TEST-75-RESOLVED under ASan/UBSan
(it should be (partly) addressed in https://github.com/systemd/systemd/pull/36353)

- [x] Reenable dfuzzer, disabled by #33185.
https://github.com/systemd/systemd/pull/34271#issuecomment-2521157877
It catches issues like https://github.com/systemd/systemd/issues/23312 and https://github.com/systemd/systemd/issues/23097

- [x] Run TEST-74-AUX-UTILS on nspawn at least one runner, currently all runner run the test on qemu.

- [ ] Also run tests on nspawn without user namespace.
- [ ] Detect huge coverage drops like https://github.com/systemd/systemd/issues/36092 automatically.
- [ ] Bring back things like the fuzz targets to the coverage report: https://github.com/systemd/systemd/pull/35407#issuecomment-2516835722
- [ ] Make systemd buildable with clang/ASan/UBSan on Debian/Ubuntu again: https://github.com/systemd/systemd/issues/35994#issuecomment-2593086920
- [ ] Provide all the logs by analogy with https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/19489/artifact//systemd-centos-ci/index.html

**Comment by yuwata** [comment]
@evverx Please add more items.

**Comment by bluca** [comment]
> * Run TEST-74-AUX-UTILS on nspawn at least one runner, currently all runner run the test on qemu.

To ensure max clarity in our CI, we need to make sure that tests that need a specific environment are separated from tests that can run anywhere, so that they can be either entirely skipped, or run fully. That way we don't get tests that are marked as successful, but actually just ran a fraction of the test cases.
With the legacy bash runner it was a problem to have many tests, as we needed to build an image for each one. But with mkosi this is no longer the case, a single image is used everywhere, so it doesn't cost anything extra to add new test cases.

This is implemented for TEST-74 here: https://github.com/systemd/systemd/pull/35349 with this PR, TEST-74 runs everything everywhere, and the VM-specific bits are in a new test case, that only runs in a VM and is clearly and unambiguously skipped elsewhere.

**Comment by evverx** [comment]
> Run TEST-74-AUX-UTILS on nspawn at least one runner

I'm not sure why it's all tied to a couple of specific test infrastructures (and why for example dfuzzer is skipped everywhere just because there aren't enough resources on GitHub). With the bash runner it was possible to run the same test in three different environments at the same time (and TEST-01-BASIC helped to make sure that all the systemd services, unit files and so on are functional in VMs and containers with/without user namespaces). I get that some testing infrastructures are constrained and all those `PREFER*` are helpful there but there are places where it isn't a problem.

**Comment by yuwata** [comment]
> three different environments at the same time

three ? qemu, nspawn and what ?

**Comment by evverx** [comment]
It was `nspawn` with and without user namespaces.

**Comment by yuwata** [comment]
> It was `nspawn` with and without user namespaces.

Thanks. Added to the list.

**Comment by evverx** [comment]
I think @DaanDeMeyer outlined some things in https://github.com/systemd/systemd/pull/35273#issuecomment-2494765968 and I think it would make sense to wait for @DaanDeMeyer's opinion on this. With coverage reports it's now possible to refactor the tests properly (instead of just guessing and hoping for the best).

At this point I think the most important thing is to actually test systemd with ASan/UBSan (instead of just compiling it, running the tests and missing all the reports).

**Comment by DaanDeMeyer** [comment]
Another issue that I filed a while back that would significantly improve test reporting: https://github.com/systemd/systemd/issues/33068

**Comment by bluca** [comment]
Is boot time really a limiting factor here? Any idea what's the rough ratio boot time vs test runtime on GHA?

**Comment by DaanDeMeyer** [comment]
> Is boot time really a limiting factor here? Any idea what's the rough ratio boot time vs test runtime on GHA?

The more granular we make the tests the more it becomes a factor.. If I look at a random Arch job the lowest time I can find it 18s for a qemu test. It might not seem much on its own but if you start adding more granular tests it quickly adds up. TEST-74-AUX-UTILS has 28 subtests, let's say the boot + processing time per qemu test is 15s. 28 * 15 = 420s or 7 minutes extra runtime if we split up TEST-74-AUX-UTILS into individual tests. (And even more for the sanitizer and coverage jobs)

**Comment by evverx** [comment]
I'm sorry for interrupting but I think it would be nice to cover the basics first. I don't think the ASan/UBsan part has been fully addressed. Looking at, for example,
```sh
../src/src/core/main.c:3033:5: runtime error: signed integer overflow: 2147483647 + 23 cannot be represented in type 'int'                                    
    #0 0x558f780cf454 in main ../src/src/core/main.c:3033                                                                                                     
    #1 0x7fc4638110c7 in __libc_start_call_main (/lib64/libc.so.6+0x40c7) (BuildId: 41939f0e8a59632286bf09e69dec833c9f0cc453)                                 
    #2 0x7fc46381118a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x418a) (BuildId: 41939f0e8a59632286bf09e69dec833c9f0cc453)                          
    #3 0x558f780adb74 in _start (/usr/lib/systemd/systemd+0x3b74) (BuildId: ce93f284628acad5bc738333347c48cc3948a37a)                                         
                                                                                                                                                              
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/src/core/main.c:3033:5 in                                                                      
Finishing after writing 0 entries                                                                                                                             
No coredumps found.                                                                                                                                           
No sanitizer issues found.
```
it doesn't look like it can handle PID1 issues. Bugs in journald can't be caught either. The `log_path` variables existed in the bash framework for a reason (they weren't bulletproof either but they made it more likely for PID1 and journald issues to be caught and reported). Without that for example dfuzzer triggering memory leaks by poking the PID1 D-Bus interface isn't as useful at it can be because those things get lost.

**Comment by evverx** [comment]
Also I've just updated the description to make it clear that dfuzzer catches issues like https://github.com/systemd/systemd/issues/23312 and https://github.com/systemd/systemd/issues/23097 so it would be really great if it was turned on.

**Comment by DaanDeMeyer** [comment]
DFUZZER was re-enabled in #33159

**Comment by evverx** [comment]
Nice! Thank you!

Eventually it would be great to teach it to discover stuff automatically (as far as I can see `org.freedesktop.sysupdate1` isn't poked for example), pass/receive file descriptors and so on. It could even go berserk and start destroying D-Bus daemons by analogy with my downstream alternative (https://seclists.org/oss-sec/2022/q4/7, https://github.com/bus1/dbus-broker/issues/291). It's unrelated to mkosi though.

**Comment by evverx** [comment]
I'd include https://github.com/systemd/systemd/issues/35964 to the list as well.

**Comment by evverx** [comment]
Looking at https://github.com/systemd/systemd/actions/runs/12719162298/job/35458882137
```sh
 1/94 systemd:integration-tests / TEST-21-DFUZZER                                               SKIP            137.98s   exit status 77
```
it doesn't seem dfuzzer is included in the coverage reports. I'm not sure if it's intentional or not but it would be great if it was included somewhere one way or another. Ideally fuzzing stuff should go to separate coverage reports to make it easier to figure out what is just fuzzed (to make sure stuff doesn't crash where it shouldn't) and what is actually tested (to make sure it actually works) but this sort of thing has never been (and unlikely to ever be) done upstream.

**Comment by evverx** [comment]
In the meantime I turned off all this stuff in my fork and other places because it isn't useful to me personally. I hope @mrc0mmand will join the discussion eventually as well to bring the perspective on actually testing systemd.

**Comment by septatrix** [comment]
Maybe unpin this, now that it is completed?

**Comment by yuwata** [comment]
Not completed, reopened.

**Comment by evverx** [comment]
By the way I think GitHub added the subissues feature to help with tracking issue like this so probably all those links leading to annoying auto-closing/reopening issues can stop.

I think it would be really nice if the CI could detect stuff like https://github.com/systemd/systemd/issues/36092 automatically by the way. I don't think it had happened before (or more precisely it happened but it was detected and fixed so nobody noticed)

**Comment by evverx** [comment]
I updated the description so the coverage bugs are included there now. I also added the bug where systemd fails to build clang/ASan/UBSan on Debian/Ubuntu. That's pretty basic stuff.

**Comment by yuwata** [comment]
@evverx Thanks.

**Comment by evverx** [comment]
@yuwata I'm not sure why you marked "Check and extract sanitizer reports". It hasn't been fully implemented. It should be possible to introduce a memory leak to PID1/journald to see that it can't be detected.

**Comment by yuwata** [comment]
You can find that in the second entry.

**Comment by evverx** [comment]
Got it. It could be I saw it when the description wasn't fully updated. I'll change it a bit and mention journald.

**Comment by evverx** [comment]
Also all those things are regressions so I'll add the regression label. I'm not sure why it's an RFE. It's OK not to fix those things of course but it should be clear that they worked and then they were broken.

**Comment by evverx** [comment]
I've just added unsymbolized ASan backtraces: https://github.com/systemd/systemd/pull/34640#issuecomment-2618858010

**Comment by evverx** [comment]
Inspired by https://github.com/systemd/systemd/issues/36351 I added the "run the resolved test under ASan" thing.

**Comment by evverx** [comment]
@yuwata I wonder why you removed the "bug" and "regression" label?

**Comment by yuwata** [comment]
I originally set this as RFE but you dropped it and set the red labels. I am not convinced that.
This is purely a list of further improvements for the current CI. Removal of some test functionalities is not a regression. We do not provide any guarantees in 'backward compatibility' of test features.
Of course, that does not mean the entries in the list are not important. We should definitely (re)implement them.
But, anyway, please do not hurry up us by setting the 'regression' label.

**Comment by evverx** [comment]
>  But, anyway, please do not hurry up us by setting the 'regression' label.

I added the regression label because things that worked no longer work. The only RFE mentioned in this thread is about some cosmetic changes to make it easier to maintain the testsuite. Everything else can be considered CI regressions making mkosi unsuitable for testing systemd under ASan properly/bisecting failures and so on. Either way as I said elsewhere it doesn't matter to me whether it's fixed or not so I don't think anyone is in a hurry here. It's a bit weird to start finding issues like https://github.com/systemd/systemd/issues/37830 in 2025 but then again I don't need mkosi for that.
